controller_manager:
  ros__parameters:
    update_rate: 100  # Adjust the rate as needed

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters: {}

joint_trajectory_controller:
  ros__parameters:
    joints:
      - thumb_proximal_yaw_joint
      - thumb_proximal_pitch_joint
      - thumb_distal_joint
      - index_proximal_joint
      - index_intermediate_joint
      - middle_proximal_joint
      - middle_intermediate_joint
      - ring_proximal_joint
      - ring_intermediate_joint
      - pinky_proximal_joint
      - pinky_intermediate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50
    action_monitor_rate: 20
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 2.0
